import requests
import json

url = "https://api.ccrdev.clickastro.com/chat/api.php"
xml = "<DATA><BIRTHDATA><SEX>Male</SEX><NAME>Tester</NAME><DAY>01</DAY><MONTH>01</MONTH><YEAR>2000</YEAR><TIME24HR>12.00.00</TIME24HR><CORR>1</CORR><PLACE>Kochi</PLACE><LONG>076.40</LONG><LAT>09.13</LAT><LONGDIR>E</LONGDIR><LATDIR>N</LATDIR><TZONE>05.30</TZONE><TZONEDIR>E</TZONEDIR></BIRTHDATA><OPTIONS><CHARTSTYLE>1</CHARTSTYLE><CHARTBORDERSTYLE>1</CHARTBORDERSTYLE><VARIANT>V0</VARIANT><LANGUAGE>ENG</LANGUAGE><REPTYPE>CC-AI</REPTYPE><REPFORMAT>HTM</REPFORMAT><CLNTID>CLICKASTRO</CLNTID><ORDID/><HSETTINGS><AYANAMSA>1</AYANAMSA><DASASYSTEM>1</DASASYSTEM><SHOWGULIKAN>1</SHOWGULIKAN><GULIKATYPE>1</GULIKATYPE><PARYANTHARSTART>0</PARYANTHARSTART><PARYANTHAREND>25</PARYANTHAREND><FAVMARPERIOD>50</FAVMARPERIOD><BHAVABALAMETHOD>1</BHAVABALAMETHOD><YEARSPREVDASAPREDREQD>0</YEARSPREVDASAPREDREQD><SUNRISEMETHOD>1</SUNRISEMETHOD><BHAVATYPE>2</BHAVATYPE><ADVANCEDOPTION1>0</ADVANCEDOPTION1><ADVANCEDOPTION2>0</ADVANCEDOPTION2><ADVANCEDOPTION3>0</ADVANCEDOPTION3><ADVANCEDOPTION4>0</ADVANCEDOPTION4></HSETTINGS><EMAIL>test@test.com</EMAIL></OPTIONS></DATA>"

payload = {'xml': xml}
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
}

print("Testing with User-Agent and form data...")
r = requests.post(url, data=payload, headers=headers)
print(f"Status: {r.status_code}")
print(f"Content: {r.text[:200]}")

print("\nTesting with direct XML body...")
r = requests.post(url, data=xml, headers={"Content-Type": "application/xml", "User-Agent": headers["User-Agent"]})
print(f"Status: {r.status_code}")
print(f"Content: {r.text[:200]}")
